package dev.heiko.universe.atmosphere;
public enum CloudType {
    FOG, HAZE, STRATUS, STRATOCUMULUS, CUMULUS, ALTOCUMULUS, ALTOSTRATUS,
    NIMBOSTRATUS, CIRRUS, CIRROSTRATUS, CIRROCUMULUS, CUMULONIMBUS
}
